"""Optional Gemini-powered AI copilot for the generated DataWonder dashboard."""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - dependency is declared in requirements.txt
    load_dotenv = None

if load_dotenv is not None:
    _module_dir = Path(__file__).resolve().parent
    _project_dir = _module_dir.parent
    for _dotenv_path in (_project_dir / ".env", _module_dir / ".env"):
        if _dotenv_path.exists():
            load_dotenv(_dotenv_path, override=False)
    load_dotenv(override=False)


SYSTEM_INSTRUCTIONS = """You are DataWonder AI assistant, an embedded business analytics copilot.

Answer only using the VERIFIED DASHBOARD CONTEXT supplied below. The context
was generated by a deterministic analytics engine from an arbitrary CSV.

Rules:
1. Never invent or estimate values, trends, fields, categories, segments,
   explanations, or recommendations.
2. If the requested information is unavailable, answer exactly:
   "Insufficient information."
3. Respect the detected schema. Never assume fields such as Date, Sales,
   Revenue, Product, Customer, Store, Category, or Region exist.
4. Treat every item in unavailable_analyses as unavailable. Do not perform or
   describe analyses that the engine skipped.
5. Clearly separate verified observations from possible explanations.
6. Recommendations must be tied to verified dashboard evidence and should
   mention uncertainty when appropriate.
7. Use the exact units, field names, and periods in the context.
8. Keep responses concise and useful for a business user.

The original row-level dataset is not provided. Do not claim to have analysed
rows or calculated anything beyond the supplied dashboard context.
"""


def _server_setting(name: str) -> str:
    """Read a deployment setting from environment variables or Streamlit Secrets."""

    environment_value = os.getenv(name, "").strip()
    if environment_value:
        return environment_value
    try:
        import streamlit as st

        return str(st.secrets.get(name, "")).strip()
    except Exception:  # noqa: BLE001 - secrets lookup must not break the chat UI
        return ""


def _server_api_key() -> str:
    """Read the deployment-owned Gemini key without exposing it in the UI."""

    return _server_setting("GEMINI_API_KEY")


def _client() -> Any:
    """Create a Gemini client from server-side configuration only."""

    api_key = _server_api_key()
    if not api_key:
        return None
    try:
        from google import genai
    except ImportError as exc:  # pragma: no cover - depends on deployment environment
        raise RuntimeError("The google-genai package is not installed. Run `pip install google-genai`.") from exc
    return genai.Client(api_key=api_key)


def _model_name(model: str | None = None) -> str:
    """Resolve the requested model from the call, environment, or Secrets."""

    return model or _server_setting("GEMINI_MODEL") or "gemini-2.0-flash"


def _available_models(client: Any) -> list[str]:
    """List text-generation models enabled for the configured Gemini key."""

    available: list[str] = []
    try:
        for item in client.models.list():
            name = str(getattr(item, "name", ""))
            actions = getattr(item, "supported_actions", None) or []
            if name.startswith("models/"):
                name = name.removeprefix("models/")
            if name and (not actions or "generateContent" in actions):
                available.append(name)
    except Exception:
        return []
    return sorted(set(available))


def _model_error_message(requested_model: str, available_models: list[str]) -> str:
    """Explain a model mismatch and show safe, actionable configuration guidance."""

    if available_models:
        preview = ", ".join(available_models[:8])
        suffix = f" Models available to this key include: {preview}."
    else:
        suffix = " The key's available model list could not be read."
    return f"Gemini model '{requested_model}' is not available for this API key.{suffix} Set GEMINI_MODEL to one of the listed model names and restart Streamlit."


def _fallback_model(available_models: list[str], requested_model: str) -> str | None:
    """Choose a compatible low-friction text model when the configured model is unavailable."""

    preferred = (
        "gemini-2.0-flash",
        "gemini-2.0-flash-001",
        "gemini-2.0-flash-lite",
        "gemini-2.0-flash-lite-001",
    )
    for candidate in preferred:
        if candidate in available_models and candidate != requested_model:
            return candidate
    return next((name for name in available_models if "flash" in name and name != requested_model), None)


def _quota_fallback_models(available_models: list[str], requested_model: str) -> list[str]:
    """Order compatible models to try when only some model quotas are exhausted."""

    preferred = (
        "gemini-2.0-flash-lite",
        "gemini-2.0-flash-lite-001",
        "gemini-2.0-flash-001",
        "gemini-2.0-flash",
    )
    ordered = [candidate for candidate in preferred if candidate in available_models and candidate != requested_model]
    ordered.extend(
        candidate for candidate in available_models
        if candidate != requested_model and "flash" in candidate and candidate not in ordered
    )
    return ordered


def _quota_fallback_model(available_models: list[str], requested_model: str) -> str | None:
    """Return the first compatible fallback for callers that need one model."""

    candidates = _quota_fallback_models(available_models, requested_model)
    return candidates[0] if candidates else None


def _history_text(history: list[dict[str, str]] | None) -> str:
    """Add a bounded, role-safe conversation window for follow-up questions."""

    if not history:
        return "No previous conversation."
    lines: list[str] = []
    for item in history[-8:]:
        role = item.get("role")
        content = item.get("content")
        if role in {"user", "assistant"} and isinstance(content, str) and content.strip():
            lines.append(f"{role.upper()}: {content[:4000]}")
    return "\n".join(lines) or "No previous conversation."


def _build_prompt(question: str, dashboard_context: str, history: list[dict[str, str]] | None) -> str:
    """Build the constrained Gemini prompt from verified dashboard output."""

    return f"""{SYSTEM_INSTRUCTIONS}

VERIFIED DASHBOARD CONTEXT:
{dashboard_context}

PREVIOUS CONVERSATION:
{_history_text(history)}

USER QUESTION:
{question}
"""


def _friendly_api_error(error: Exception) -> str:
    """Turn Gemini SDK failures into actionable, secret-safe UI messages."""

    raw_message = str(error)
    safe_message = re.sub(r"AIza[0-9A-Za-z_-]{20,}", "[redacted-key]", raw_message)
    safe_message = re.sub(r"sk-[A-Za-z0-9_-]{20,}", "[redacted-key]", safe_message)
    status = getattr(error, "status_code", None) or getattr(error, "code", None)
    status_text = str(status) if status is not None else ""
    combined = f"{status_text} {safe_message}".lower()

    if "429" in combined or "quota" in combined or "resource_exhausted" in combined:
        retry_match = re.search(r"retry(?: in| after)?\s*([0-9]+(?:\.[0-9]+)?)s", safe_message, flags=re.IGNORECASE)
        retry_hint = f" Retry after about {retry_match.group(1)} seconds." if retry_match else ""
        detail = safe_message.strip().replace("\n", " ")[:360]
        return (
            "Gemini returned 429 RESOURCE_EXHAUSTED. This may be a model-specific RPM, TPM, RPD, "
            "spend, or temporary throttling limit even when the overall dashboard appears below quota."
            f"{retry_hint} API detail: {detail or 'No additional detail was returned.'}"
        )

    if "401" in combined or "api key not valid" in combined or "invalid api key" in combined:
        return "Gemini rejected the server API key. Check GEMINI_API_KEY in .env or Streamlit Secrets and generate a new key if needed."
    if "403" in combined or "permission" in combined or "permission_denied" in combined:
        return "Gemini denied this request. Check that the Gemini API is enabled for the key's project and that the key has permission to use the selected model."
    if "404" in combined or "not found" in combined or "model" in combined and "not available" in combined:
        return "The configured Gemini model is unavailable. Set GEMINI_MODEL to a model enabled for this API key, for example gemini-2.5-flash."
    if "timeout" in combined or "connection" in combined or "network" in combined:
        return "The Gemini service could not be reached. Check the network connection and try again."
    detail = safe_message.strip().replace("\n", " ")[:240]
    return f"Gemini request failed. Check the server configuration and model name. Details: {detail or type(error).__name__}"


def answer_question(
    question: str,
    analysis_context: str,
    history: list[dict[str, str]] | None = None,
    model: str | None = None,
) -> str:
    """Answer using Gemini and only the serialized dashboard context."""

    question = (question or "").strip()
    if not question:
        return "Please enter a question about the generated dashboard."
    if not analysis_context or not analysis_context.strip():
        return "Insufficient information."

    try:
        client = _client()
    except RuntimeError as exc:
        return str(exc)
    if client is None:
        return "The AI copilot is unavailable because the server has not been configured with GEMINI_API_KEY."

    requested_model = _model_name(model)
    prompt = _build_prompt(question, analysis_context, history)
    try:
        response = client.models.generate_content(model=requested_model, contents=prompt)
        content = getattr(response, "text", None)
        return content.strip() if content else "Insufficient information."
    except Exception as exc:  # noqa: BLE001 - user-facing API boundary
        error_text = str(exc).lower()
        if "429" in error_text or "resource_exhausted" in error_text:
            available_models = _available_models(client)
            fallback_errors: list[Exception] = []
            for fallback in _quota_fallback_models(available_models, requested_model):
                try:
                    fallback_response = client.models.generate_content(model=fallback, contents=prompt)
                    fallback_content = getattr(fallback_response, "text", None)
                    if fallback_content:
                        return fallback_content.strip()
                except Exception as fallback_exc:  # noqa: BLE001 - preserve detailed quota diagnostics
                    fallback_errors.append(fallback_exc)
                    if "429" not in str(fallback_exc).lower() and "resource_exhausted" not in str(fallback_exc).lower():
                        return _friendly_api_error(fallback_exc)
            if fallback_errors:
                return _friendly_api_error(fallback_errors[-1])
            return _friendly_api_error(exc)
        if "404" in error_text or "not found" in error_text or "model" in error_text and "not available" in error_text:
            available_models = _available_models(client)
            fallback = _fallback_model(available_models, requested_model)
            if fallback:
                try:
                    fallback_response = client.models.generate_content(model=fallback, contents=prompt)
                    fallback_content = getattr(fallback_response, "text", None)
                    if fallback_content:
                        return fallback_content.strip()
                except Exception as fallback_exc:  # noqa: BLE001 - preserve actionable fallback error
                    return _friendly_api_error(fallback_exc)
            return _model_error_message(requested_model, available_models)
        return _friendly_api_error(exc)
